import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "./components/ThemeProvider";
import Navbar from "./components/Navbar";
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

export const metadata: Metadata = {
  title: "Francisco Alvarado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`} >
      <body className="bg-slate-100 dark:bg-zinc-900 text-black dark:text-white">    
        <ThemeProvider >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
