import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./components/ThemeProvider";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Francisco Alvarado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className} >
      <body className="bg-white dark:bg-black text-black dark:text-white">
        
        <ThemeProvider >
        <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
