import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "./components/ThemeProvider";
import Navbar from "./components/Navbar";
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import Footer from "./components/Footer";

export const metadata: Metadata = {
    title: "Francisco",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: "/favicon/favicon.ico", sizes: "any" },
            { url: "/favicon/favicon-16x16.png", type: "image/png", sizes: "16x16" },
            { url: "/favicon/favicon-32x32.png", type: "image/png", sizes: "32x32" },
        ],
        apple: "/favicon/apple-touch-icon.png",
    },
    manifest: "/site.webmanifest",
};

export default function RootLayout({
    children,
}:{
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`} >
            <body className="bg-slate-100 dark:bg-zinc-900 text-black dark:text-white max-w-full sm:max-w-[640px] md:max-w-[800px] m-auto">
                <ThemeProvider >
                    <Navbar />
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
